### ISSUE TITLE
Log In Operation Not Working

### ISSUE THREAD

**Issue by VicStelmak** [carlfranklin/IdentityManagerLibrary#1]
It is impossible to log in onto the program. First of all you need to fix _LoginPartial.cshtml page to make it possible to see Login and Register options in Blazor anyway but then it is impossible to log in and program always write: Invalid login attempt.

**Comment by carlfranklin** [comment]
My demo was not clear. I apologize. I never intended for you to be able to log into the admin app (**IdentityManagerBlazorServer**). To test the auth, I've added a new Blazor Server project called **AuthDemo**. I updated the README to include instructions for creating **AuthDemo** and clarified the issue. Hope this helps.

**Comment by carlfranklin** [comment]
I have closed the issue
